SELECT * FROM `SALARIOS` WHERE PROFISSÃO LIKE 'P%';
SELECT * FROM `SALARIOS` WHERE PROFISSÃO LIKE 'M%';
SELECT * FROM `SALARIOS` WHERE PROFISSÃO LIKE 'A%';
SELECT * FROM `SALARIOS` WHERE PROFISSÃO LIKE 'T%';
SELECT * FROM `SALARIOS` WHERE PROFISSÃO LIKE 'J%';



SELECT SUM(SALÁRIO) AS SOMASAL_PROF FROM `SALARIOS`WHERE PROFISSÃO = 'PROFESSOR';


SELECT AVG(SALÁRIO) AS MEDIA_SALARIOS FROM `SALARIOS`WHERE PROFISSÃO = 'PROFESSOR';


SELECT MAX(SALÁRIO) AS MAIOR-SALARIO FROM `SALARIOS`WHERE PROFISSÃO = 'PROFESSOR';


SELECT MIN(SALÁRIO) AS MENOS_SALARIO FROM `SALARIOS`WHERE PROFISSÃO = 'PROFESSOR';


SELECT MAX(SALÁRIO) AS MAIOR_SALARIO FROM SALARIOS WHERE PROFISSÃO IN ('ATOR', 'MÚSICO');


SELECT MAX(SALÁRIO) AS MAIOR_SALARIO FROM SALARIOS WHERE PROFISSÃO IN ('ATOR', 'MÚSICO', 'JODADOR DE FUTEBOL');
